name: Deploy to WordPress.org

on:
  release:
    types: [published]

jobs:
  tag:
    name: New release

    runs-on: ubuntu-latest

    steps:
      # installing
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.2'
      - run: npm install -g npm@8.3.2

       # debug
      - run: node --version
      - run: npm --version
      - run: git branch -v

      # build
      - run: make build-production

      # release on wp.org
      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: "entity-viewer"
